### ISSUE TITLE
Delta Chat removes 'new' flag from all mail in all mailboxes

### ISSUE THREAD

**Issue by spanezz** [r10s/messenger-android#25]
Hello,

I connected once to my IMAP account with Delta Chat, and all NEW email in all mailboxes now still shows as unread but not as NEW anymore.

That was a surprising behaviour for me: both that Delta Chat went and read through all my mailboxes, and that it changed flags on messages it shouldn't have anything to do with.

**Comment by r10s** [comment]
Hmm, I cannot reproduce this here. Which email-provider do you use?

Delta Chat only sets the SEEN flag and does not remove flags, see https://github.com/r10s/messenger-backend/blob/master/src/mrimap.c#L1475 , however, we've just fixed some other strange behaviours [here](https://github.com/r10s/messenger-backend/commit/b711919abf371209aa1eeb16df085eec67ee3880), maybe this was a side effect.

If the problem is still present in the upcoming release (v0.1.19 or larger), please re-open this issue. For now, it is closed.

**Comment by r10s** [comment]
maybe this is similar to #115 , which, however, is more clearly defined.
