### ISSUE TITLE
Web.de: port 465/starttls smtp not supported

### ISSUE THREAD

**Issue by thesnable** [r10s/messenger-android#51]
No Error message..Just the little clocl behind sent messages
they never go out
account installation error free (why?)

**Comment by joergister** [comment]
Because web.de uses port 587 for SMTP.
https://hilfe.web.de/pop-imap/imap/imap-serverdaten.html

**Comment by joergister** [comment]
And because auf this. https://github.com/r10s/messenger-android/issues/46

**Comment by Rochambeau** [comment]
All members of my family use web.de and a lot of my friends. 

Would be great if we all could leave Wh***A** a switch to delta chat. 

Sadly noone i know can code good enough to fix this problem by himself.

**Comment by r10s** [comment]
No problem, I'll fix this as soon I find some time for it.

**Comment by r10s** [comment]
Should work with the upcoming 0.1.22, however, here I have still some problems with the IDLE command, not sure if this is delayed by web.de

**Comment by r10s** [comment]
web.de works just fine in 0.1.22 - IDLE does work, however, by some options web.de does not add new messages to INBOX but to "Unknown senders", so they do not pop up in Delta Chat immediately. 

However, this is by design and no bug - change the web.de default option, add the sender to your web.de-friends or use another provider.
